name: matomo
description: Cross-platform Matomo tracking for Flutter, using the Matomo API and written in pure Dart.
version: 0.1.2
homepage: https://github.com/poitch/dart-matomo
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.27.1'

dependencies:
  flutter:
    sdk: flutter
  fk_user_agent:
    git:
      url: https://github.com/OneXeor/fk_user_agent.git
      ref: versions-update
  http: ^1.1.0
  logging: ^1.0.1
  package_info_plus: ^8.1.2
  shared_preferences: ^2.0.5
  universal_html: ^2.0.7
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
